### ISSUE TITLE
Issue while compiling with the csmagazine class

### ISSUE THREAD

**Issue by prabhuramachandran** [sdwareham/CS-LaTeX#1]
When I compile `cs.tex` I run into the following error:
```
$ pdflatex cs.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./cs.tex
LaTeX2e <2016/03/31>
Babel <3.9r> and hyphenation patterns for 83 language(s) loaded.
[...]
(/usr/local/texlive/2016/texmf-dist/tex/latex/ms/everysel.sty)))
! Missing number, treated as zero.
<to be read again>
                   J
l.32
```
If I ignore the error and continue along, it seems to work but I'd like to know how I could fix this.  As you can see I am using TexLive from 2016.

Thank you!

**Comment by sdwareham** [comment]
Please try with TeXLive 2017. We have not tested with 2016. This might be a known bug in this older version.

**Comment by prabhuramachandran** [comment]
Thanks.  I will do that after I upgrade which till take a bit of time.

**Comment by sdwareham** [comment]
If you would like to send me your article files (TeX, bib, any referenced graphics, etc.) I can test on TeXLive 2017 for you to make sure that solves the issue.

**Comment by prabhuramachandran** [comment]
Thanks, I just tested with TexLive 2018 and it works fine.  I will close this issue.
